name: Bun CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: oven-sh/setup-bun@v2
    - name: Install dependencies
      run: bun install
      working-directory: ./frontend
    - name: Run eslint
      run: bun run lint
      working-directory: ./frontend
    - name: Check formatting
      run: bun prettier . --check
      working-directory: ./frontend
    
